/* script.js — PDF Suite Pro */

// 1️⃣ D'ABORD : Définir les traductions (AVANT l'IIFE)
window.translations = {
  fr: {
    'head.title': 'PDF Suite Pro — Outils PDF professionnels',
    'head.description': 'Suite PDF complète : conversion, fusion, compression, protection.',
    'nav.tools': 'Outils',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.ai': 'Support IA',
    'header.login': 'Connexion',
    'header.signup': 'S\'inscrire',
    'hero.title': 'Suite PDF professionnelle — rapide, sûre, intelligente',
    'hero.lead': 'Convertissez, fusionnez, compressez et protégez vos PDF en quelques clics.',
    'hero.stats.users': 'Utilisateurs',
    'hero.stats.rating': 'Note moyenne',
    'hero.stats.files': 'Fichiers traités',
    'hero.cta.tools': 'Essayer les outils',
    'hero.cta.ai': 'Tester l\'IA',
    'tools.badge': 'Outils',
    'tools.title': 'Outils PDF complets',
    'tools.subtitle': 'Cartes épurées, icônes SVG, actions claires.',
    'tools.premium.title': 'Débloquez les fonctionnalités Premium',
    'tools.premium.description': 'Signature numérique, protection avancée, édition complète.',
    'tools.premium.cta': 'Passer à Premium',
    'badge.free': 'Gratuit',
    'badge.premium': 'Premium',
    'card.pdfword.title': 'PDF vers Word',
    'card.pdfword.desc': 'Convertir PDF en Word modifiable.',
    'card.wordpdf.title': 'Word vers PDF',
    'card.wordpdf.desc': 'Convertir documents Word en PDF.',
    'card.jpgpdf.title': 'JPG vers PDF',
    'card.jpgpdf.desc': 'Assembler des images en PDF.',
    'card.merge.title': 'Fusionner PDF',
    'card.merge.desc': 'Combiner plusieurs PDF.',
    'card.split.title': 'Diviser PDF',
    'card.split.desc': 'Séparer en plusieurs fichiers.',
    'card.compress.title': 'Compresser PDF',
    'card.compress.desc': 'Réduire la taille du PDF.',
    'card.rotate.title': 'Pivoter PDF',
    'card.rotate.desc': 'Faire pivoter des pages.',
    'card.protect.title': 'Protéger PDF',
    'card.protect.desc': 'Ajouter un mot de passe.',
    'card.unlock.title': 'Déverrouiller PDF',
    'card.unlock.desc': 'Supprimer les restrictions.',
    'card.sign.title': 'Signer PDF',
    'card.sign.desc': 'Ajouter signature numérique.',
    'card.watermark.title': 'Filigrane',
    'card.watermark.desc': 'Ajouter un filigrane.',
    'card.edit.title': 'Éditer PDF',
    'card.edit.desc': 'Modifier texte et images.',
    'card.button.open': 'Ouvrir',
    'card.button.try': 'Essayer',
    'features.badge': 'Fonctionnalités',
    'features.title': 'Pourquoi choisir PDF Suite Pro ?',
    'features.subtitle': 'Découvrez ce qui rend PDF Suite Pro unique.',
    'features.security.title': 'Sécurité maximale',
    'features.security.desc': 'Vos fichiers sont cryptés et supprimés automatiquement.',
    'features.speed.title': 'Ultra-rapide',
    'features.speed.desc': 'Traitement en quelques secondes.',
    'features.accuracy.title': 'Précision parfaite',
    'features.accuracy.desc': 'Préservation de la mise en page originale.',
    'features.cloud.title': '100% en ligne',
    'features.cloud.desc': 'Aucune installation requise.',
    'features.ai.title': 'Assistant IA',
    'features.ai.desc': 'Support intelligent 24/7.',
    'features.quality.title': 'Qualité pro',
    'features.quality.desc': 'Utilisé par plus d\'un million de professionnels.',
    'pricing.badge': 'Tarifs',
    'pricing.title': 'Choisissez votre plan',
    'pricing.subtitle': 'Des plans adaptés à tous les besoins.',
    'pricing.free.title': 'Gratuit',
    'pricing.free.period': '/mois',
    'pricing.free.feature1': '6 outils essentiels',
    'pricing.free.feature2': '2 fichiers/heure',
    'pricing.free.feature3': 'Taille max: 10 MB',
    'pricing.free.cta': 'Commencer gratuitement',
    'pricing.premium.title': 'Premium',
    'pricing.premium.period': '/mois',
    'pricing.premium.feature1': '12 outils complets',
    'pricing.premium.feature2': 'Fichiers illimités',
    'pricing.premium.feature3': 'Taille max: 100 MB',
    'pricing.premium.feature4': 'Support prioritaire',
    'pricing.premium.feature5': 'Signature numérique',
    'pricing.premium.cta': 'Passer à Premium',
    'pricing.enterprise.title': 'Entreprise',
    'pricing.enterprise.custom': 'Sur mesure',
    'pricing.enterprise.feature1': 'Tout Premium +',
    'pricing.enterprise.feature2': 'API dédiée',
    'pricing.enterprise.feature3': 'Multi-utilisateurs',
    'pricing.enterprise.feature4': 'Support 24/7',
    'pricing.enterprise.cta': 'Nous contacter',
    'ai.badge': 'Intelligence Artificielle',
    'ai.title': 'Support IA 24/7',
    'ai.subtitle': 'Votre assistant intelligent pour toutes vos questions PDF.',
    'ai.demo.title': 'Posez vos questions en langage naturel',
    'ai.demo.desc': 'Notre IA comprend vos besoins et vous guide.',
    'ai.demo.cta': 'Essayer l\'assistant IA',
    'ai.chat.title': 'Assistant IA',
    'ai.chat.status': 'En ligne',
    'ai.chat.intro': 'Bonjour ! 👋 Comment puis-je vous aider aujourd\'hui ?',
    'ai.chat.placeholder': 'Posez votre question...',
    'ai.chat.send': 'Envoyer',
    'ai.quick.pdf_word': 'PDF → Word',
    'ai.quick.merge': 'Fusionner PDF',
    'ai.quick.compress': 'Compresser',
    'ai.response.pdf_word': 'Pour convertir un PDF en Word, utilisez notre outil "PDF vers Word". Il préserve la mise en page originale.',
    'ai.response.merge_pdf': 'Notre outil "Fusionner PDF" vous permet de combiner plusieurs documents PDF en un seul fichier.',
    'ai.response.premium_query': 'Les fonctionnalités Premium débloquent des outils avancés comme la signature numérique et la protection par mot de passe.',
    'ai.response.greeting': 'Bonjour ! Je suis l\'assistant IA de PDF Suite Pro. N\'hésitez pas si vous avez des questions.',
    'ai.response.contact': 'Si vous ne trouvez pas votre réponse ici, contactez notre support client.',
    'ai.response.compress_size': 'L\'outil "Compresser PDF" réduit la taille de vos fichiers sans perte significative de qualité.',
    'ai.response.protect_pdf': 'Vous pouvez protéger vos PDF avec un mot de passe grâce à notre outil "Protéger PDF" (Premium).',
    'ai.response.fallback': 'Je suis là pour répondre à vos questions. Pouvez-vous préciser ce que vous recherchez ?',
    'cookie.message': '🍪 Nous utilisons des cookies essentiels pour améliorer votre expérience.',
    'cookie.settings': 'Gérer',
    'cookie.accept': 'Accepter',
    'footer.tagline': 'Suite complète pour vos PDF. Rapide, sûre, professionnelle.',
    'footer.product.title': 'Produit',
    'footer.support.title': 'Support',
    'footer.legal.title': 'Légal',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.cookies': 'Cookies',
    'footer.help': 'Centre d\'aide',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 PDF Suite Pro. Tous droits réservés.',
    'modal.preview.title': 'Aperçu du traitement',
    'modal.preview.upload': 'Parcourir les fichiers',
    'modal.drop.text': 'Glissez-déposez vos fichiers ici',
    'modal.drop.or': 'ou',
    'modal.cancel': 'Annuler',
    'modal.confirm': 'Lancer le traitement',
    'modal.close': 'Fermer'
  },
  en: {
    'head.title': 'PDF Suite Pro — Professional PDF Tools',
    'head.description': 'Complete PDF suite: convert, merge, compress, protect.',
    'nav.tools': 'Tools',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.ai': 'AI Support',
    'header.login': 'Log In',
    'header.signup': 'Sign Up',
    'hero.title': 'Professional PDF Suite — Fast, Secure, Smart',
    'hero.lead': 'Convert, merge, compress, and protect your PDFs in a few clicks.',
    'hero.stats.users': 'Users',
    'hero.stats.rating': 'Average rating',
    'hero.stats.files': 'Files processed',
    'hero.cta.tools': 'Try Tools',
    'hero.cta.ai': 'Test AI',
    'tools.badge': 'Tools',
    'tools.title': 'Complete PDF Tools',
    'tools.subtitle': 'Clean cards, SVG icons, clear actions.',
    'tools.premium.title': 'Unlock Premium Features',
    'tools.premium.description': 'Digital signature, advanced protection, full editing.',
    'tools.premium.cta': 'Go Premium',
    'badge.free': 'Free',
    'badge.premium': 'Premium',
    'card.pdfword.title': 'PDF to Word',
    'card.pdfword.desc': 'Convert PDF to editable Word.',
    'card.wordpdf.title': 'Word to PDF',
    'card.wordpdf.desc': 'Convert Word documents to PDF.',
    'card.jpgpdf.title': 'JPG to PDF',
    'card.jpgpdf.desc': 'Assemble images into PDF.',
    'card.merge.title': 'Merge PDF',
    'card.merge.desc': 'Combine multiple PDFs.',
    'card.split.title': 'Split PDF',
    'card.split.desc': 'Split into multiple files.',
    'card.compress.title': 'Compress PDF',
    'card.compress.desc': 'Reduce PDF file size.',
    'card.rotate.title': 'Rotate PDF',
    'card.rotate.desc': 'Rotate pages.',
    'card.protect.title': 'Protect PDF',
    'card.protect.desc': 'Add a password.',
    'card.unlock.title': 'Unlock PDF',
    'card.unlock.desc': 'Remove restrictions.',
    'card.sign.title': 'Sign PDF',
    'card.sign.desc': 'Add digital signature.',
    'card.watermark.title': 'Watermark',
    'card.watermark.desc': 'Add a watermark.',
    'card.edit.title': 'Edit PDF',
    'card.edit.desc': 'Edit text and images.',
    'card.button.open': 'Open',
    'card.button.try': 'Try',
    'features.badge': 'Features',
    'features.title': 'Why choose PDF Suite Pro?',
    'features.subtitle': 'Discover what makes PDF Suite Pro unique.',
    'features.security.title': 'Maximum security',
    'features.security.desc': 'Your files are encrypted and deleted automatically.',
    'features.speed.title': 'Ultra-fast',
    'features.speed.desc': 'Processing in seconds.',
    'features.accuracy.title': 'Perfect accuracy',
    'features.accuracy.desc': 'Preserves original layout.',
    'features.cloud.title': '100% online',
    'features.cloud.desc': 'No installation required.',
    'features.ai.title': 'AI Assistant',
    'features.ai.desc': '24/7 intelligent support.',
    'features.quality.title': 'Pro quality',
    'features.quality.desc': 'Used by over a million professionals.',
    'pricing.badge': 'Pricing',
    'pricing.title': 'Choose your plan',
    'pricing.subtitle': 'Plans for every need.',
    'pricing.free.title': 'Free',
    'pricing.free.period': '/month',
    'pricing.free.feature1': '6 essential tools',
    'pricing.free.feature2': '2 files/hour',
    'pricing.free.feature3': 'Max size: 10 MB',
    'pricing.free.cta': 'Start for free',
    'pricing.premium.title': 'Premium',
    'pricing.premium.period': '/month',
    'pricing.premium.feature1': '12 complete tools',
    'pricing.premium.feature2': 'Unlimited files',
    'pricing.premium.feature3': 'Max size: 100 MB',
    'pricing.premium.feature4': 'Priority support',
    'pricing.premium.feature5': 'Digital signature',
    'pricing.premium.cta': 'Go Premium',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.custom': 'Custom',
    'pricing.enterprise.feature1': 'Everything in Premium +',
    'pricing.enterprise.feature2': 'Dedicated API',
    'pricing.enterprise.feature3': 'Multi-user',
    'pricing.enterprise.feature4': '24/7 support',
    'pricing.enterprise.cta': 'Contact us',
    'ai.badge': 'Artificial Intelligence',
    'ai.title': '24/7 AI Support',
    'ai.subtitle': 'Your smart assistant for all your PDF questions.',
    'ai.demo.title': 'Ask questions in natural language',
    'ai.demo.desc': 'Our AI understands your needs and guides you.',
    'ai.demo.cta': 'Try AI assistant',
    'ai.chat.title': 'AI Assistant',
    'ai.chat.status': 'Online',
    'ai.chat.intro': 'Hello! 👋 How can I help you today?',
    'ai.chat.placeholder': 'Type your question...',
    'ai.chat.send': 'Send',
    'ai.quick.pdf_word': 'PDF → Word',
    'ai.quick.merge': 'Merge PDF',
    'ai.quick.compress': 'Compress',
    'ai.response.pdf_word': 'To convert a PDF to Word, use our "PDF to Word" tool. It preserves the original layout.',
    'ai.response.merge_pdf': 'Our "Merge PDF" tool allows you to combine multiple PDF documents into a single file.',
    'ai.response.premium_query': 'Premium features unlock advanced tools like digital signatures and password protection.',
    'ai.response.greeting': 'Hello! I am the AI assistant for PDF Suite Pro. Feel free to ask any questions.',
    'ai.response.contact': 'If you can\'t find your answer here, contact our customer support.',
    'ai.response.compress_size': 'The "Compress PDF" tool reduces the size of your files without significant loss of quality.',
    'ai.response.protect_pdf': 'You can protect your PDFs with a password using our "Protect PDF" tool (Premium).',
    'ai.response.fallback': 'I am here to answer your questions. Can you clarify what you are looking for?',
    'cookie.message': '🍪 We use essential cookies to improve your experience.',
    'cookie.settings': 'Manage',
    'cookie.accept': 'Accept',
    'footer.tagline': 'Complete suite for your PDFs. Fast, secure, professional.',
    'footer.product.title': 'Product',
    'footer.support.title': 'Support',
    'footer.legal.title': 'Legal',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.help': 'Help Center',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 PDF Suite Pro. All rights reserved.',
    'modal.preview.title': 'Processing preview',
    'modal.preview.upload': 'Browse files',
    'modal.drop.text': 'Drag and drop your files here',
    'modal.drop.or': 'or',
    'modal.cancel': 'Cancel',
    'modal.confirm': 'Start processing',
    'modal.close': 'Close'
  },
  es: {
    'head.title': 'PDF Suite Pro — Herramientas PDF profesionales',
    'head.description': 'Suite PDF completa: convierte, fusiona, comprime, protege.',
    'nav.tools': 'Herramientas',
    'nav.features': 'Funciones',
    'nav.pricing': 'Precios',
    'nav.ai': 'Soporte IA',
    'header.login': 'Iniciar sesión',
    'header.signup': 'Registrarse',
    'hero.title': 'Suite PDF profesional — Rápida, segura, inteligente',
    'hero.lead': 'Convierta, fusione, comprima y proteja sus PDF en unos pocos clics.',
    'hero.stats.users': 'Usuarios',
    'hero.stats.rating': 'Calificación media',
    'hero.stats.files': 'Archivos procesados',
    'hero.cta.tools': 'Probar herramientas',
    'hero.cta.ai': 'Probar IA',
    'tools.badge': 'Herramientas',
    'tools.title': 'Herramientas PDF completas',
    'tools.subtitle': 'Tarjetas limpias, iconos SVG, acciones claras.',
    'tools.premium.title': 'Desbloquear funciones Premium',
    'tools.premium.description': 'Firma digital, protección avanzada, edición completa.',
    'tools.premium.cta': 'Ir a Premium',
    'badge.free': 'Gratis',
    'badge.premium': 'Premium',
    'card.pdfword.title': 'PDF a Word',
    'card.pdfword.desc': 'Convierte PDF a Word editable.',
    'card.wordpdf.title': 'Word a PDF',
    'card.wordpdf.desc': 'Convierte Word a PDF.',
    'card.jpgpdf.title': 'JPG a PDF',
    'card.jpgpdf.desc': 'Ensambla imágenes en PDF.',
    'card.merge.title': 'Fusionar PDF',
    'card.merge.desc': 'Combina varios PDF.',
    'card.split.title': 'Dividir PDF',
    'card.split.desc': 'Divide en varios archivos.',
    'card.compress.title': 'Comprimir PDF',
    'card.compress.desc': 'Reduce el tamaño del PDF.',
    'card.rotate.title': 'Rotar PDF',
    'card.rotate.desc': 'Rotar páginas.',
    'card.protect.title': 'Proteger PDF',
    'card.protect.desc': 'Añadir contraseña.',
    'card.unlock.title': 'Desbloquear PDF',
    'card.unlock.desc': 'Eliminar restricciones.',
    'card.sign.title': 'Firmar PDF',
    'card.sign.desc': 'Añadir firma digital.',
    'card.watermark.title': 'Marca de agua',
    'card.watermark.desc': 'Añadir marca de agua.',
    'card.edit.title': 'Editar PDF',
    'card.edit.desc': 'Editar texto e imágenes.',
    'card.button.open': 'Abrir',
    'card.button.try': 'Probar',
    'features.badge': 'Funciones',
    'features.title': '¿Por qué elegir PDF Suite Pro?',
    'features.subtitle': 'Descubra lo que hace único a PDF Suite Pro.',
    'features.security.title': 'Seguridad máxima',
    'features.security.desc': 'Sus archivos se cifran y eliminan automáticamente.',
    'features.speed.title': 'Ultra-rápido',
    'features.speed.desc': 'Procesamiento en segundos.',
    'features.accuracy.title': 'Precisión perfecta',
    'features.accuracy.desc': 'Conserva el diseño original.',
    'features.cloud.title': '100% en línea',
    'features.cloud.desc': 'No requiere instalación.',
    'features.ai.title': 'Asistente IA',
    'features.ai.desc': 'Soporte inteligente 24/7.',
    'features.quality.title': 'Calidad profesional',
    'features.quality.desc': 'Usado por más de un millón de profesionales.',
    'pricing.badge': 'Precios',
    'pricing.title': 'Elija su plan',
    'pricing.subtitle': 'Planes para cada necesidad.',
    'pricing.free.title': 'Gratis',
    'pricing.free.period': '/mes',
    'pricing.free.feature1': '6 herramientas esenciales',
    'pricing.free.feature2': '2 archivos/hora',
    'pricing.free.feature3': 'Tamaño máx: 10 MB',
    'pricing.free.cta': 'Empezar gratis',
    'pricing.premium.title': 'Premium',
    'pricing.premium.period': '/mes',
    'pricing.premium.feature1': '12 herramientas completas',
    'pricing.premium.feature2': 'Archivos ilimitados',
    'pricing.premium.feature3': 'Tamaño máx: 100 MB',
    'pricing.premium.feature4': 'Soporte prioritario',
    'pricing.premium.feature5': 'Firma digital',
    'pricing.premium.cta': 'Ir a Premium',
    'pricing.enterprise.title': 'Empresa',
    'pricing.enterprise.custom': 'Personalizado',
    'pricing.enterprise.feature1': 'Todo en Premium +',
    'pricing.enterprise.feature2': 'API dedicada',
    'pricing.enterprise.feature3': 'Multiusuario',
    'pricing.enterprise.feature4': 'Soporte 24/7',
    'pricing.enterprise.cta': 'Contáctenos',
    'ai.badge': 'Inteligencia Artificial',
    'ai.title': 'Soporte IA 24/7',
    'ai.subtitle': 'Su asistente inteligente para todas sus preguntas PDF.',
    'ai.demo.title': 'Haga preguntas en lenguaje natural',
    'ai.demo.desc': 'Nuestra IA comprende sus necesidades y le guía.',
    'ai.demo.cta': 'Probar asistente IA',
    'ai.chat.title': 'Asistente IA',
    'ai.chat.status': 'En línea',
    'ai.chat.intro': '¡Hola! 👋 ¿Cómo puedo ayudarle hoy?',
    'ai.chat.placeholder': 'Escriba su pregunta...',
    'ai.chat.send': 'Enviar',
    'ai.quick.pdf_word': 'PDF → Word',
    'ai.quick.merge': 'Fusionar PDF',
    'ai.quick.compress': 'Comprimir',
    'ai.response.pdf_word': 'Para convertir un PDF a Word, utilice nuestra herramienta "PDF a Word". Conserva el diseño original.',
    'ai.response.merge_pdf': 'Nuestra herramienta "Fusionar PDF" le permite combinar varios documentos PDF en un solo archivo.',
    'ai.response.premium_query': 'Las funciones Premium desbloquean herramientas avanzadas como firmas digitales y protección con contraseña.',
    'ai.response.greeting': '¡Hola! Soy el asistente de IA de PDF Suite Pro. No dude en hacer cualquier pregunta.',
    'ai.response.contact': 'Si no puede encontrar su respuesta aquí, contacte a nuestro soporte.',
    'ai.response.compress_size': 'La herramienta "Comprimir PDF" reduce el tamaño de sus archivos sin pérdida significativa de calidad.',
    'ai.response.protect_pdf': 'Puede proteger sus PDF con una contraseña usando nuestra herramienta "Proteger PDF" (Premium).',
    'ai.response.fallback': 'Estoy aquí para responder a sus preguntas. ¿Puede aclarar lo que busca?',
    'cookie.message': '🍪 Utilizamos cookies esenciales para mejorar su experiencia.',
    'cookie.settings': 'Gestionar',
    'cookie.accept': 'Aceptar',
    'footer.tagline': 'Suite completa para sus PDFs. Rápida, segura, profesional.',
    'footer.product.title': 'Producto',
    'footer.support.title': 'Soporte',
    'footer.legal.title': 'Legal',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.cookies': 'Cookies',
    'footer.help': 'Centro de ayuda',
    'footer.contact': 'Contacto',
    'footer.copyright': '© 2025 PDF Suite Pro. Todos los derechos reservados.',
    'modal.preview.title': 'Vista previa del procesamiento',
    'modal.preview.upload': 'Examinar archivos',
    'modal.drop.text': 'Arrastre y suelte sus archivos aquí',
    'modal.drop.or': 'o',
    'modal.cancel': 'Cancelar',
    'modal.confirm': 'Iniciar procesamiento',
    'modal.close': 'Cerrar'
  },
  ar: {
    'head.title': 'مجموعة PDF برو — أدوات PDF احترافية',
    'head.description': 'مجموعة PDF كاملة: تحويل، دمج، ضغط، حماية.',
    'nav.tools': 'الأدوات',
    'nav.features': 'الميزات',
    'nav.pricing': 'الأسعار',
    'nav.ai': 'دعم الذكاء الاصطناعي',
    'header.login': 'تسجيل الدخول',
    'header.signup': 'التسجيل',
    'hero.title': 'مجموعة PDF الاحترافية — سريعة، آمنة، ذكية',
    'hero.lead': 'حوّل، ادمج، اضغط، واحمِ ملفات PDF الخاصة بك ببضع نقرات.',
    'hero.stats.users': 'المستخدمون',
    'hero.stats.rating': 'التقييم المتوسط',
    'hero.stats.files': 'الملفات المعالجة',
    'hero.cta.tools': 'جرب الأدوات',
    'hero.cta.ai': 'اختبر الذكاء الاصطناعي',
    'tools.badge': 'الأدوات',
    'tools.title': 'أدوات PDF كاملة',
    'tools.subtitle': 'بطاقات نظيفة، أيقونات SVG، إجراءات واضحة.',
    'tools.premium.title': 'افتح الميزات المميزة',
    'tools.premium.description': 'التوقيع الرقمي، الحماية المتقدمة، التحرير الكامل.',
    'tools.premium.cta': 'الترقية إلى بريميوم',
    'badge.free': 'مجاني',
    'badge.premium': 'مميز',
    'card.pdfword.title': 'PDF إلى Word',
    'card.pdfword.desc': 'تحويل PDF إلى Word قابل للتحرير.',
    'card.wordpdf.title': 'Word إلى PDF',
    'card.wordpdf.desc': 'تحويل Word إلى PDF.',
    'card.jpgpdf.title': 'JPG إلى PDF',
    'card.jpgpdf.desc': 'تجميع الصور في PDF.',
    'card.merge.title': 'دمج PDF',
    'card.merge.desc': 'دمج عدة ملفات PDF.',
    'card.split.title': 'تقسيم PDF',
    'card.split.desc': 'تقسيم إلى عدة ملفات.',
    'card.compress.title': 'ضغط PDF',
    'card.compress.desc': 'تقليل حجم PDF.',
    'card.rotate.title': 'تدوير PDF',
    'card.rotate.desc': 'تدوير الصفحات.',
    'card.protect.title': 'حماية PDF',
    'card.protect.desc': 'إضافة كلمة مرور.',
    'card.unlock.title': 'إلغاء قفل PDF',
    'card.unlock.desc': 'إزالة القيود.',
    'card.sign.title': 'توقيع PDF',
    'card.sign.desc': 'إضافة توقيع رقمي.',
    'card.watermark.title': 'علامة مائية',
    'card.watermark.desc': 'إضافة علامة مائية.',
    'card.edit.title': 'تعديل PDF',
    'card.edit.desc': 'تعديل النصوص والصور.',
    'card.button.open': 'فتح',
    'card.button.try': 'تجربة',
    'features.badge': 'الميزات',
    'features.title': 'لماذا تختار PDF Suite Pro؟',
    'features.subtitle': 'اكتشف ما يميز PDF Suite Pro.',
    'features.security.title': 'أمان قصوى',
    'features.security.desc': 'يتم تشفير ملفاتك وحذفها تلقائيًا.',
    'features.speed.title': 'سريع للغاية',
    'features.speed.desc': 'معالجة في ثوانٍ.',
    'features.accuracy.title': 'دقة مثالية',
    'features.accuracy.desc': 'يحافظ على التخطيط الأصلي.',
    'features.cloud.title': '100% عبر الإنترنت',
    'features.cloud.desc': 'لا يتطلب تثبيت.',
    'features.ai.title': 'مساعد الذكاء الاصطناعي',
    'features.ai.desc': 'دعم ذكي 24/7.',
    'features.quality.title': 'جودة احترافية',
    'features.quality.desc': 'يستخدمه أكثر من مليون محترف.',
    'pricing.badge': 'الأسعار',
    'pricing.title': 'اختر خطتك',
    'pricing.subtitle': 'خطط لكل احتياج.',
    'pricing.free.title': 'مجاني',
    'pricing.free.period': '/شهر',
    'pricing.free.feature1': '6 أدوات أساسية',
    'pricing.free.feature2': 'ملفان/ساعة',
    'pricing.free.feature3': 'الحد الأقصى: 10 ميغابايت',
    'pricing.free.cta': 'ابدأ مجانًا',
    'pricing.premium.title': 'بريميوم',
    'pricing.premium.period': '/شهر',
    'pricing.premium.feature1': '12 أداة كاملة',
    'pricing.premium.feature2': 'ملفات غير محدودة',
    'pricing.premium.feature3': 'الحد الأقصى: 100 ميغابايت',
    'pricing.premium.feature4': 'دعم أولوية',
    'pricing.premium.feature5': 'توقيع رقمي',
    'pricing.premium.cta': 'الترقية إلى بريميوم',
    'pricing.enterprise.title': 'المؤسسات',
    'pricing.enterprise.custom': 'مخصص',
    'pricing.enterprise.feature1': 'كل شيء في بريميوم +',
    'pricing.enterprise.feature2': 'API مخصص',
    'pricing.enterprise.feature3': 'متعدد المستخدمين',
    'pricing.enterprise.feature4': 'دعم 24/7',
    'pricing.enterprise.cta': 'اتصل بنا',
    'ai.badge': 'الذكاء الاصطناعي',
    'ai.title': 'دعم الذكاء الاصطناعي 24/7',
    'ai.subtitle': 'مساعدك الذكي لجميع أسئلتك حول PDF.',
    'ai.demo.title': 'اطرح أسئلة بلغة طبيعية',
    'ai.demo.desc': 'يفهم الذكاء الاصطناعي احتياجاتك ويرشدك.',
    'ai.demo.cta': 'جرب مساعد الذكاء الاصطناعي',
    'ai.chat.title': 'مساعد الذكاء الاصطناعي',
    'ai.chat.status': 'متصل',
    'ai.chat.intro': 'مرحبا! 👋 كيف يمكنني مساعدتك اليوم؟',
    'ai.chat.placeholder': 'اكتب سؤالك...',
    'ai.chat.send': 'إرسال',
    'ai.quick.pdf_word': 'PDF → Word',
    'ai.quick.merge': 'دمج PDF',
    'ai.quick.compress': 'ضغط',
    'ai.response.pdf_word': 'لتحويل PDF إلى Word، استخدم أداة "PDF إلى Word". تحافظ على التخطيط الأصلي.',
    'ai.response.merge_pdf': 'تتيح لك أداة "دمج PDF" دمج عدة مستندات PDF في ملف واحد.',
    'ai.response.premium_query': 'تفتح الميزات المميزة أدوات متقدمة مثل التوقيعات الرقمية والحماية بكلمة مرور.',
    'ai.response.greeting': 'مرحبا! أنا مساعد الذكاء الاصطناعي لـ PDF Suite Pro. لا تتردد في طرح أي أسئلة.',
    'ai.response.contact': 'إذا لم تجد إجابتك هنا، اتصل بدعم العملاء.',
    'ai.response.compress_size': 'أداة "ضغط PDF" تقلل حجم ملفاتك دون فقدان كبير في الجودة.',
    'ai.response.protect_pdf': 'يمكنك حماية ملفات PDF بكلمة مرور باستخدام أداة "حماية PDF" (بريميوم).',
    'ai.response.fallback': 'أنا هنا للإجابة على أسئلتك. هل يمكنك توضيح ما تبحث عنه؟',
    'cookie.message': '🍪 نستخدم ملفات تعريف الارتباط الأساسية لتحسين تجربتك.',
    'cookie.settings': 'إدارة',
    'cookie.accept': 'قبول',
    'footer.tagline': 'مجموعة كاملة لملفات PDF الخاصة بك. سريعة، آمنة، احترافية.',
    'footer.product.title': 'المنتج',
    'footer.support.title': 'الدعم',
    'footer.legal.title': 'قانوني',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.cookies': 'ملفات تعريف الارتباط',
    'footer.help': 'مركز المساعدة',
    'footer.contact': 'اتصل',
    'footer.copyright': '© 2025 PDF Suite Pro. جميع الحقوق محفوظة.',
    'modal.preview.title': 'معاينة المعالجة',
    'modal.preview.upload': 'تصفح الملفات',
    'modal.drop.text': 'اسحب وأفلت ملفاتك هنا',
    'modal.drop.or': 'أو',
    'modal.cancel': 'إلغاء',
    'modal.confirm': 'بدء المعالجة',
    'modal.close': 'إغلاق'
  }
};

// 2️⃣ ENSUITE : Tout le reste du code dans l'IIFE
(() => {
  'use strict';

  // ... (tout le reste de ton code JavaScript ici)
  
})();